config/routes.rb
Rails.application.routes.draw do
  resources :microposts, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :following
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Ancient-Headland - TWOOT</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="/">Home</a></li>
	        <% if signed_in? %>
	        	<li><%= link_to "Users", users_path %></li>
	        <% end %>
	      </ul>

	      <ul class="nav navbar-nav navbar-right">
	      	<% if signed_in? %>
	      		<li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><%= link_to "Profile", user_path(current_user)%></li>
		            <li><%= link_to "Settings", edit_user_path(current_user)%></li>
		            <li role="separator" class="divider"></li>
		           <li><%=link_to "Sign out", signout_path, method: "delete" %></li>
		          </ul>
		        </li>
	      	<% else %>
	      		<li> <%=link_to "Sign in", signin_path %></li>
	      	<% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

<div class="container-fluid">
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<%= yield %>
</div>
</body>
</html>